import { KanbanIssuesInterface } from "../../../types/kanban/issues";

export const kanbanAllIssues: Array<KanbanIssuesInterface> = [
  {
    id: 1,
    title: "Dev (web):Articles: Show letest comments first.",
    type_id: 1,
    issue_slug: 'pr-001',
    priority_id: 1,
    assignee: {
      id: 1,
      name: 'Somnath Sardar',
      email: 'somnath@example.com',
      avatar: 'https://i.pravatar.cc/150?u=somnath@example.com',
    },
    kanban_column_id: 1,
    project_id: 1,
  },
  {
    id: 2,
    title: "Frontend & Backend Flow for Affiliates",
    type_id: 2,
    issue_slug: 'pr-002',
    priority_id: 2,
    assignee: {
      id: 2,
      name: 'Deep Paul',
      email: 'deep@example.com',
      avatar: 'https://i.pravatar.cc/150?u=deep@example.com',
    },
    kanban_column_id: 2,
    project_id: 1,
  },
  {
    id: 3,
    title: "Urban Global : Add the RSS feed under Events - U",
    type_id: 2,
    issue_slug: 'pr-003',
    priority_id: 3,
    assignee: {
      id: 4,
      name: 'Sonali Das',
      email: 'sonali@example.com',
      avatar: 'https://i.pravatar.cc/150?u=sonali@example.com',
    },
    kanban_column_id: 1,
    project_id: 1,
  },
  {
    id: 4,
    title: "Leave Group' option MISSING from front-end on Open Free Groups",
    type_id: 2,
    issue_slug: 'pr-004',
    priority_id: 3,
    assignee: {
      id: 3,
      name: 'Sourav Gupta',
      email: 'sourav@example.com',
      avatar: 'https://i.pravatar.cc/150?u=sourav@example.com',
    },
    kanban_column_id: 2,
    project_id: 1,
  },
  {
    id: 5,
    title: "Leave Group' option MISSING from front-end on Open Free Groups",
    type_id: 2,
    issue_slug: 'pr-004',
    priority_id: 3,
    assignee: {
      id: 3,
      name: 'Sourav Gupta',
      email: 'sourav@example.com',
      avatar: 'https://i.pravatar.cc/150?u=sourav@example.com',
    },
    kanban_column_id: 1,
    project_id: 1,
  },
  {
    id: 6,
    title: "Leave Group' option MISSING from front-end on Open Free Groups",
    type_id: 2,
    issue_slug: 'pr-004',
    priority_id: 3,
    assignee: {
      id: 3,
      name: 'Sourav Gupta',
      email: 'sourav@example.com',
      avatar: 'https://i.pravatar.cc/150?u=sourav@example.com',
    },
    kanban_column_id: 3,
    project_id: 1,
  },
  {
    id: 7,
    title: "Leave Group' option MISSING from front-end on Open Free Groups",
    type_id: 2,
    issue_slug: 'pr-004',
    priority_id: 3,
    assignee: {
      id: 3,
      name: 'Sourav Gupta',
      email: 'sourav@example.com',
      avatar: 'https://i.pravatar.cc/150?u=sourav@example.com',
    },
    kanban_column_id: 1,
    project_id: 1,
  },
  {
    id: 8,
    title: "Leave Group' option MISSING from front-end on Open Free Groups",
    type_id: 2,
    issue_slug: 'pr-004',
    priority_id: 3,
    assignee: {
      id: 3,
      name: 'Sourav Gupta',
      email: 'sourav@example.com',
      avatar: 'https://i.pravatar.cc/150?u=sourav@example.com',
    },
    kanban_column_id: 4,
    project_id: 1,
  },
  {
    id: 9,
    title: "Leave Group' option MISSING from front-end on Open Free Groups",
    type_id: 2,
    issue_slug: 'pr-004',
    priority_id: 3,
    assignee: {
      id: 3,
      name: 'Sourav Gupta',
      email: 'sourav@example.com',
      avatar: 'https://i.pravatar.cc/150?u=sourav@example.com',
    },
    kanban_column_id: 1,
    project_id: 1,
  },
  {
    id: 10,
    title: "Leave Group' option MISSING from front-end on Open Free Groups",
    type_id: 2,
    issue_slug: 'pr-004',
    priority_id: 3,
    assignee: {
      id: 3,
      name: 'Sourav Gupta',
      email: 'sourav@example.com',
      avatar: 'https://i.pravatar.cc/150?u=sourav@example.com',
    },
    kanban_column_id: 1,
    project_id: 1,
  },
]